name: finpath
description: "student financial path"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.3
  restart_app: ^1.2.1
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.4
  telephony: ^0.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
