import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/cloud_transaction.dart';
import '../models/cloud_insight.dart';

class CloudService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Stream of transactions from Firestore for the current user
  Stream<List<CloudTransaction>> getTransactionsStream() {
    String? uid = _auth.currentUser?.uid;
    if (uid == null) return Stream.value([]);

    return _db
        .collection('transactions')
        .where('userId', isEqualTo: uid)
        // .orderBy('date', descending: true) // Temporarily commented out while index builds
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => CloudTransaction.fromFirestore(doc))
            .toList());
  }

  // Stream of insights generated by Python (stored in a separate collection)
  Stream<CloudInsight?> getInsightsStream() {
    String? uid = _auth.currentUser?.uid;
    if (uid == null) return Stream.value(null);

    return _db.collection('insights').doc(uid).snapshots().map((doc) {
      if (!doc.exists) return null;
      return CloudInsight.fromFirestore(doc);
    });
  }

  Future<String?> getUserId() async {
    return _auth.currentUser?.uid;
  }

  Future<void> updatePhysicalCash(double amount) async {
    String? uid = _auth.currentUser?.uid;
    if (uid == null) return;

    await _db.collection('audits').doc(uid).set({
      'cash_on_hand': amount,
      'last_updated': FieldValue.serverTimestamp(),
    });
  }
}
